openapi: 3.0.0
info:
  title: Sports API
  version: 1.0.0
paths:
  /api/sports:
    get:
      summary: Get all sports
      responses:
        "200":
          description: List of sports
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
