import prisma from "@/lib/prisma";
import { NextAuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import bcrypt from "bcryptjs";

// Auth user type for internal use
type AuthUser = {
  id: string;
  email: string;
  name: string;
  roleId: number | null;
  onboardingComplete: boolean;
  password: string;
  publicUuid: string;
  username: string;
};

// AuthService class - Prisma implementation
export class AuthService {
  static async getUserByEmail(email: string): Promise<AuthUser | null> {
    const user = await prisma.user.findUnique({
      where: { email },
      include: { attributes: true },
    });

    if (!user) return null;

    return {
      id: user.id.toString(),
      email: user.email,
      name: user.username,
      roleId: user.roleId,
      onboardingComplete: user.isOnboardingComplete ?? false,
      password: user.password ?? "",
      publicUuid: user.publicUuid,
      username: user.username,
    };
  }

  static async getUserById(id: string): Promise<AuthUser | null> {
    const user = await prisma.user.findUnique({
      where: { id: parseInt(id) },
    });

    if (!user) return null;

    return {
      id: user.id.toString(),
      email: user.email,
      name: user.username,
      roleId: user.roleId,
      onboardingComplete: user.isOnboardingComplete ?? false,
      password: user.password ?? "",
      publicUuid: user.publicUuid,
      username: user.username,
    };
  }

  static async updateOnboardingComplete(id: string): Promise<void> {
    await prisma.user.update({
      where: { id: parseInt(id) },
      data: { isOnboardingComplete: true },
    });
  }

  static async checkUsernameExists(username: string): Promise<boolean> {
    const user = await prisma.user.findUnique({
      where: { username },
      select: { id: true },
    });
    return user !== null;
  }

  static async checkRoleExists(roleId: number): Promise<boolean> {
    const role = await prisma.profileRole.findUnique({
      where: { id: roleId },
      select: { id: true },
    });
    return role !== null;
  }

  static async registerUser(
    email: string,
    hashedPassword: string,
    username: string,
    roleId: number
  ): Promise<AuthUser> {
    const user = await prisma.user.create({
      data: {
        email,
        password: hashedPassword,
        username,
        roleId,
        // publicUuid is auto-generated by DB default
      },
    });

    return {
      id: user.id.toString(),
      email: user.email,
      name: user.username,
      roleId: user.roleId,
      onboardingComplete: user.isOnboardingComplete ?? false,
      password: user.password ?? "",
      publicUuid: user.publicUuid,
      username: user.username,
    };
  }
}

// NextAuth configuration
export const authOptions: NextAuthOptions = {
  providers: [
    CredentialsProvider({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        try {
          const user = await AuthService.getUserByEmail(credentials.email);

          if (!user) {
            return null;
          }

          const isValid = await bcrypt.compare(
            credentials.password,
            user.password
          );

          if (!isValid) {
            return null;
          }

          return {
            id: user.id.toString(),
            email: user.email,
            name: user.name,
            roleId: user.roleId,
            onboardingComplete: user.onboardingComplete,
            publicUuid: user.publicUuid,
            username: user.username,
          };
        } catch (error) {
          console.error("Auth error:", error);
          return null;
        }
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        // During sign-in, use the user data
        token.roleId = user.roleId;
        token.onboardingComplete = user.onboardingComplete;
        // Add publicUuid and username
        const dbUser = await AuthService.getUserById(user.id);
        if (dbUser) {
          token.publicUuid = dbUser.publicUuid;
          token.username = dbUser.username;
        }
      } else if (token.sub) {
        // For session updates, query the database for fresh data
        const dbUser = await AuthService.getUserById(token.sub);
        if (dbUser) {
          token.roleId = dbUser.roleId;
          token.onboardingComplete = dbUser.onboardingComplete;
          token.publicUuid = dbUser.publicUuid;
          token.username = dbUser.username;
        }
      }
      return token;
    },
    async session({ session, token }) {
      if (token) {
        session.user.id = token.sub!;
        session.user.roleId = token.roleId as number;
        session.user.onboardingComplete = token.onboardingComplete as boolean;
        session.user.publicUuid = token.publicUuid as string;
        session.user.username = token.username as string;
      }
      return session;
    },
  },
  pages: {
    // signIn: "/", // Use default signin page
  },
};
