openapi: 3.0.3
info:
  title: User Profile API
  version: 1.0.0
  description: API contracts for user profile viewing, editing, and image upload.

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /profile/{userId}:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "404":
          description: Profile not found
        "401":
          description: Unauthorized
    put:
      summary: Update user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
      responses:
        "200":
          description: Profile updated
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (not owner)
  /upload:
    post:
      summary: Generate presigned URL for image upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        "200":
          description: Presigned URL generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized

components:
  schemas:
    UserProfile:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        team:
          type: string
        location:
          type: string
        bio:
          type: string
        coverImageUrl:
          type: string
          format: uri
        profileImageUrl:
          type: string
          format: uri
        openToOpportunities:
          type: boolean
    UpdateProfileRequest:
      type: object
      properties:
        bio:
          type: string
          maxLength: 500
        openToOpportunities:
          type: boolean
        coverImageUrl:
          type: string
          format: uri
        profileImageUrl:
          type: string
          format: uri
    UploadRequest:
      type: object
      required:
        - fileName
        - fileType
        - userId
      properties:
        fileName:
          type: string
        fileType:
          type: string
          enum: [image/jpeg, image/png, image/webp]
        userId:
          type: string
          format: uuid
    UploadResponse:
      type: object
      properties:
        signedUrl:
          type: string
          format: uri
        key:
          type: string
